---
- hosts: "localhost"
  vars_files:
    - defaults/main.yml
  tasks:
    - name: Playbook entry
      include_tasks: tasks/main.yml
      tags: always

  roles:
    - role: gantsign.golang
    - role: diodonfrost.ohmyzsh
    - role: diodonfrost.p10k
    - role: gantsign.visual-studio-code

  become: yes
  roles:
    - role: buluma.hashicorp