- name: Clone user dotfiles
  git: repo={{ dotfiles.url }} dest=/tmp/{{ dotfiles.destination }} accept_hostkey=yes update=no force=yes
  become: yes
  become_user: "{{ username }}"

- name: move and replace .config
  ansible.builtin.copy:
    src: /tmp/movetodotfile/.config
    dest: /home/{{ username }}
    force: yes
    owner: "{{ username }}"
    group: "{{ username }}"

- name: move and replace mountain background
  copy:
   src: mountain.jpg
   dest: /home/{{ username }}/Pictures
   force: True 
   mode: u+rw,g+xr,o+x

- name: move and replace .zshrc
  ansible.builtin.copy:
    src: /tmp/movetodotfile/.zshrc
    dest: /home/{{ username }}
    force: yes
    owner: "{{ username }}"
    group: "{{ username }}"

- name: give execute permision to bspwm
  ansible.builtin.file: 
    path: /home/{{ username }}/.config/bspwm/bspwmrc
    mode: a+x

- name: give execute permision to poly script
  ansible.builtin.file: 
    path: /home/{{ username }}/.config/polybar/launch.sh
    mode: a+x 
