---

- name: List user with home directory
  shell: ls -1 /home
  register: linux_users
  changed_when: false
  when: user_list == []

- name: Set linux_users to list
  set_fact:
    user_list: "{{ linux_users.stdout_lines | list + ['root'] }}"
  when: user_list == []



- name: Package | Install os packages
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ os_packages }}"
  become: true

- name: Installing docker
  import_tasks: "docker.yml"
  when: install_docker
  tags: always
  become: true

- name: Installing fonts
  import_tasks: "fonts.yml"
  when: install_fonts
  tags: always
  become: true

- name: Installing zips
  import_tasks: "zip.yml"
  when: install_zip
  tags: always
  become: true

- name: Installing gaming
  import_tasks: "gaming.yml"
  when: install_gaming
  tags: always
  become: true

- name: Installing chat
  import_tasks: "chat.yml"
  when: install_chat
  tags: always
  become: true
