---
- name: Include OS specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  tags: always

- name: Updating os
  include_tasks: "tasks/update.yml"
  tags: always

- name: Include req
  include_tasks: "tasks/install.yml"
  tags: always

- name: install chat apps
  include_tasks: chat.yml
  when: install_chat == true

- name: install zip apps
  include_tasks: zip.yml
  tags: always

- name: install gaming packages
  include_tasks: gaming.yml
  when: install_gaming == true

- name: install fonts
  include_tasks: fonts.yml
  when: install_fonts == true

- name: install dotfiles
  include_tasks: dotfiles.yml
  when: install_dotfiles == true

  

#- name: Containers | Docker and Podman
#  include_vars: "vars/Containers.yml"
#  tags: always